// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pingable.proto

/*
Package pingablepb is a generated protocol buffer package.

It is generated from these files:
	pingable.proto

It has these top-level messages:
	NodeMember
	PingRequest
	PingResponse
	MsgRequest
	MsgResponse
*/
package pingablepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 成员节点
type NodeMember struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	MasterId       string `protobuf:"bytes,2,opt,name=masterId" json:"masterId,omitempty"`
	LastRegistered string `protobuf:"bytes,3,opt,name=lastRegistered" json:"lastRegistered,omitempty"`
	ServiceAddr    string `protobuf:"bytes,4,opt,name=serviceAddr" json:"serviceAddr,omitempty"`
	ClusterId      string `protobuf:"bytes,5,opt,name=clusterId" json:"clusterId,omitempty"`
}

func (m *NodeMember) Reset()                    { *m = NodeMember{} }
func (m *NodeMember) String() string            { return proto.CompactTextString(m) }
func (*NodeMember) ProtoMessage()               {}
func (*NodeMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeMember) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeMember) GetMasterId() string {
	if m != nil {
		return m.MasterId
	}
	return ""
}

func (m *NodeMember) GetLastRegistered() string {
	if m != nil {
		return m.LastRegistered
	}
	return ""
}

func (m *NodeMember) GetServiceAddr() string {
	if m != nil {
		return m.ServiceAddr
	}
	return ""
}

func (m *NodeMember) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

// 心跳请求结构体
type PingRequest struct {
	FromId   string `protobuf:"bytes,1,opt,name=fromId" json:"fromId,omitempty"`
	MasterId string `protobuf:"bytes,2,opt,name=masterId" json:"masterId,omitempty"`
	MetaData string `protobuf:"bytes,3,opt,name=metaData" json:"metaData,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingRequest) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *PingRequest) GetMasterId() string {
	if m != nil {
		return m.MasterId
	}
	return ""
}

func (m *PingRequest) GetMetaData() string {
	if m != nil {
		return m.MetaData
	}
	return ""
}

// 心跳响应结构体
type PingResponse struct {
	Code     int32         `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg      string        `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Members  []*NodeMember `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	MasterId string        `protobuf:"bytes,4,opt,name=masterId" json:"masterId,omitempty"`
	MetaData string        `protobuf:"bytes,5,opt,name=metaData" json:"metaData,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PingResponse) GetMembers() []*NodeMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *PingResponse) GetMasterId() string {
	if m != nil {
		return m.MasterId
	}
	return ""
}

func (m *PingResponse) GetMetaData() string {
	if m != nil {
		return m.MetaData
	}
	return ""
}

// 消息请求结构体
type MsgRequest struct {
	FromId string `protobuf:"bytes,1,opt,name=fromId" json:"fromId,omitempty"`
	ToId   string `protobuf:"bytes,2,opt,name=toId" json:"toId,omitempty"`
	MsgId  string `protobuf:"bytes,3,opt,name=msgId" json:"msgId,omitempty"`
	Action string `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	Data   string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *MsgRequest) Reset()                    { *m = MsgRequest{} }
func (m *MsgRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgRequest) ProtoMessage()               {}
func (*MsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgRequest) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *MsgRequest) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func (m *MsgRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *MsgRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MsgRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 消息想用结构体
type MsgResponse struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	MsgId  string `protobuf:"bytes,3,opt,name=msgId" json:"msgId,omitempty"`
	Action string `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	Data   string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *MsgResponse) Reset()                    { *m = MsgResponse{} }
func (m *MsgResponse) String() string            { return proto.CompactTextString(m) }
func (*MsgResponse) ProtoMessage()               {}
func (*MsgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MsgResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MsgResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *MsgResponse) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *MsgResponse) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MsgResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeMember)(nil), "pingablepb.NodeMember")
	proto.RegisterType((*PingRequest)(nil), "pingablepb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "pingablepb.PingResponse")
	proto.RegisterType((*MsgRequest)(nil), "pingablepb.MsgRequest")
	proto.RegisterType((*MsgResponse)(nil), "pingablepb.MsgResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PingableInterface service

type PingableInterfaceClient interface {
	// ping 心跳服务
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// msg 消息服务 用于接收同伴发送来的消息
	Msg(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error)
}

type pingableInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewPingableInterfaceClient(cc *grpc.ClientConn) PingableInterfaceClient {
	return &pingableInterfaceClient{cc}
}

func (c *pingableInterfaceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/pingablepb.PingableInterface/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingableInterfaceClient) Msg(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := grpc.Invoke(ctx, "/pingablepb.PingableInterface/Msg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingableInterface service

type PingableInterfaceServer interface {
	// ping 心跳服务
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// msg 消息服务 用于接收同伴发送来的消息
	Msg(context.Context, *MsgRequest) (*MsgResponse, error)
}

func RegisterPingableInterfaceServer(s *grpc.Server, srv PingableInterfaceServer) {
	s.RegisterService(&_PingableInterface_serviceDesc, srv)
}

func _PingableInterface_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingableInterfaceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingablepb.PingableInterface/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingableInterfaceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingableInterface_Msg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingableInterfaceServer).Msg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingablepb.PingableInterface/Msg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingableInterfaceServer).Msg(ctx, req.(*MsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingableInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pingablepb.PingableInterface",
	HandlerType: (*PingableInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingableInterface_Ping_Handler,
		},
		{
			MethodName: "Msg",
			Handler:    _PingableInterface_Msg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pingable.proto",
}

func init() { proto.RegisterFile("pingable.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xa5, 0x49, 0xfa, 0xb3, 0x13, 0x29, 0x3a, 0x48, 0x1b, 0x8a, 0x87, 0x92, 0x83, 0xf4,
	0x54, 0xa4, 0x5e, 0x04, 0x4f, 0x82, 0x97, 0x1c, 0x2a, 0x25, 0x77, 0x0f, 0x9b, 0xec, 0x34, 0x04,
	0x9a, 0x6c, 0xcc, 0x6e, 0x3d, 0xf8, 0x11, 0xfc, 0x10, 0xe2, 0x47, 0x95, 0x6c, 0x37, 0x4d, 0xff,
	0x40, 0x45, 0xbc, 0xcd, 0x7b, 0x33, 0x79, 0xf3, 0xf6, 0x6d, 0x16, 0xfa, 0x65, 0x56, 0xa4, 0x2c,
	0x5e, 0xd1, 0xb4, 0xac, 0x84, 0x12, 0x08, 0x0d, 0x2e, 0xe3, 0xe0, 0xcb, 0x02, 0x78, 0x16, 0x9c,
	0xe6, 0x94, 0xc7, 0x54, 0x61, 0x1f, 0x3a, 0x19, 0xf7, 0xad, 0xb1, 0x35, 0xe9, 0x45, 0x9d, 0x8c,
	0xe3, 0x08, 0xce, 0x72, 0x26, 0x15, 0x55, 0x21, 0xf7, 0x3b, 0x9a, 0xdd, 0x62, 0xbc, 0x81, 0xfe,
	0x8a, 0x49, 0x15, 0x51, 0x9a, 0xd5, 0x0c, 0x71, 0xdf, 0xd6, 0x13, 0x07, 0x2c, 0x8e, 0xc1, 0x93,
	0x54, 0xbd, 0x65, 0x09, 0x3d, 0x72, 0x5e, 0xf9, 0x8e, 0x1e, 0xda, 0xa5, 0xf0, 0x1a, 0x7a, 0xc9,
	0x6a, 0x6d, 0xd6, 0xb8, 0xba, 0xdf, 0x12, 0xc1, 0x0b, 0x78, 0x8b, 0xac, 0x48, 0x23, 0x7a, 0x5d,
	0x93, 0x54, 0x38, 0x80, 0xee, 0xb2, 0x12, 0x79, 0xd8, 0xd8, 0x34, 0xe8, 0xa4, 0xd5, 0xba, 0x47,
	0x8a, 0x3d, 0x31, 0xc5, 0x8c, 0xc9, 0x2d, 0x0e, 0x3e, 0x2d, 0x38, 0xdf, 0xe8, 0xcb, 0x52, 0x14,
	0x92, 0x10, 0xc1, 0x49, 0x04, 0x27, 0x2d, 0xef, 0x46, 0xba, 0xc6, 0x0b, 0xb0, 0x73, 0x99, 0x1a,
	0xdd, 0xba, 0xc4, 0x5b, 0xf8, 0x9f, 0xeb, 0xcc, 0xa4, 0x6f, 0x8f, 0xed, 0x89, 0x37, 0x1b, 0x4c,
	0xdb, 0x58, 0xa7, 0x6d, 0xa4, 0x51, 0x33, 0xb6, 0x67, 0xd0, 0x39, 0x61, 0xd0, 0x3d, 0x30, 0xf8,
	0x0e, 0x30, 0x97, 0x3f, 0x1e, 0x1f, 0xc1, 0x51, 0x62, 0x7b, 0x74, 0x5d, 0xe3, 0x15, 0xb8, 0xb9,
	0x4c, 0xc3, 0xe6, 0x62, 0x36, 0xa0, 0x56, 0x60, 0x89, 0xca, 0x44, 0x61, 0x5c, 0x18, 0x54, 0x2b,
	0xf0, 0x76, 0xbf, 0xae, 0x83, 0x35, 0x78, 0x7a, 0xf7, 0xaf, 0xa2, 0xf9, 0xf3, 0xda, 0xd9, 0x87,
	0x05, 0x97, 0x0b, 0x93, 0x66, 0x58, 0x28, 0xaa, 0x96, 0x2c, 0x21, 0x7c, 0x00, 0xa7, 0x26, 0x71,
	0xb8, 0x9b, 0xf4, 0xce, 0xaf, 0x31, 0xf2, 0x8f, 0x1b, 0x1b, 0xe3, 0xc1, 0x3f, 0xbc, 0x07, 0x7b,
	0x2e, 0x53, 0xdc, 0xbb, 0xa5, 0x36, 0xd6, 0xd1, 0xf0, 0x88, 0x6f, 0xbe, 0x8c, 0xbb, 0xfa, 0xd5,
	0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x3f, 0xed, 0x18, 0x47, 0x03, 0x00, 0x00,
}
